### ISSUE TITLE
Play DRM content

### ISSUE THREAD

**Issue by marksdemellin** [brunochanrio/DangoPlayer#15]
Hello, I have problems to play my DRM protected contents. This is the format, but seems not decrypting...

#EXTINF:-1 ,channel
#KODIPROP:inputstream.adaptive.license_type=clearkey
#KODIPROP:inputstream.adaptive.license_key={"keys":[{"kty":"oct","kid":"","k":""}],"type":"temporary"}
https:/.....mpd

I have tried also with
#KODIPROP:inputstream.adaptive.license_key={"":""}
but not working also in this case

**Comment by brunochanrio** [comment]
At the moment DangoPlayer only supports keys stored in a file loaded from a URL

**Comment by brunochanrio** [comment]
Good news, a new versión of DangoPlayer, 2.1.1keroppi_rev1, has been released recently, and now supports DRM Keys stored in M3U Lists
