### ISSUE TITLE
can't find the code source

### ISSUE THREAD

**Issue by yassbra10** [brunochanrio/DangoPlayer#2]
hi developer, how can I download the Dangoplayer code source ?? i try to download it but the file is empty.

**Comment by brunochanrio** [comment]
The app is closed source so you will not be able to download the source code

**Comment by brunochanrio** [comment]
<img alt='Information about source code releasing' width='660' src='https://brunochanrio.github.io/DangoPlayer/assets/AntiFOSS_Warning.png'/>
