### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [brunochanrio/DangoPlayer#6]
Please support the Android 13 "Themed App Icons" feature.

![Screenshot_2023-03-11-22-38-40-113_de mm20 launcher2 release](https://user-images.githubusercontent.com/23485114/224507165-bb30c091-fcb3-45e3-b3ce-81a887e88457.jpg)

**Comment by brunochanrio** [comment]
The Monochrome Icon was not added for now because the app is still
targeting Android 12, when the app targets Android 13 the Monochrome Icon
will be added, and please uninstall Firefox and install a Chromium-based
browser, Firefox is better on iOS

**Comment by xmha97** [comment]
Thanks for adding the monochrome icon.

---

The only reason I use Firefox is because it supports extensions.

Do you know a browser that is based on Chromium and supports extensions?

![Screenshot_2023-03-12-00-49-35-879_org.mozilla.fenix.jpg](https://user-images.githubusercontent.com/23485114/224512031-d6f02dc4-49d6-47eb-ac7e-ed6427715629.jpg)

**Comment by brunochanrio** [comment]
You can use Kiwi Browser, is a Chromium-based browser that supports
extensions from the Chrome Web Store

Download:
https://play.google.com/store/apps/details?id=com.kiwibrowser.browser

**Comment by xmha97** [comment]
OK, thank you.
I installed Kiwi Browser.

**Comment by brunochanrio** [comment]
The Monochrome icon is added on the new release of DangoPlayer Uni
